const flagByTeamName: Record<string, string> = {
  Algeria: "🇩🇿",
  Argentina: "🇦🇷",
  Australia: "🇦🇺",
  Austria: "🇦🇹",
  Belgium: "🇧🇪",
  "Bosnia and Herzegovina": "🇧🇦",
  "Bosnia-Herzegovina": "🇧🇦",
  Brazil: "🇧🇷",
  "Cape Verde": "🇨🇻",
  "Cape Verde Islands": "🇨🇻",
  "Cabo Verde": "🇨🇻",
  Canada: "🇨🇦",
  Chile: "🇨🇱",
  Colombia: "🇨🇴",
  "Costa Rica": "🇨🇷",
  "South Korea": "🇰🇷",
  "Korea Republic": "🇰🇷",
  "Republic of Korea": "🇰🇷",
  "Ivory Coast": "🇨🇮",
  "Côte d'Ivoire": "🇨🇮",
  "Cote d'Ivoire": "🇨🇮",
  Croatia: "🇭🇷",
  Curaçao: "🇨🇼",
  Curacao: "🇨🇼",
  Denmark: "🇩🇰",
  Ecuador: "🇪🇨",
  Egypt: "🇪🇬",
  England: "\u{1F3F4}\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}",
  France: "🇫🇷",
  Germany: "🇩🇪",
  Ghana: "🇬🇭",
  Haiti: "🇭🇹",
  Haïti: "🇭🇹",
  Iran: "🇮🇷",
  Iraq: "🇮🇶",
  Italy: "🇮🇹",
  Jamaica: "🇯🇲",
  Japan: "🇯🇵",
  Jordan: "🇯🇴",
  Mexico: "🇲🇽",
  Morocco: "🇲🇦",
  Netherlands: "🇳🇱",
  Holland: "🇳🇱",
  "New Zealand": "🇳🇿",
  Norway: "🇳🇴",
  Panama: "🇵🇦",
  Paraguay: "🇵🇾",
  Peru: "🇵🇪",
  Poland: "🇵🇱",
  Portugal: "🇵🇹",
  Qatar: "🇶🇦",
  Czechia: "🇨🇿",
  "Czech Republic": "🇨🇿",
  "DR Congo": "🇨🇩",
  "Congo DR": "🇨🇩",
  "Democratic Republic of the Congo": "🇨🇩",
  "Saudi Arabia": "🇸🇦",
  Scotland: "\u{1F3F4}\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}",
  Senegal: "🇸🇳",
  Serbia: "🇷🇸",
  "South Africa": "🇿🇦",
  Spain: "🇪🇸",
  Sweden: "🇸🇪",
  Switzerland: "🇨🇭",
  Turkey: "🇹🇷",
  Türkiye: "🇹🇷",
  Turkiye: "🇹🇷",
  Tunisia: "🇹🇳",
  Ukraine: "🇺🇦",
  "United Arab Emirates": "🇦🇪",
  UAE: "🇦🇪",
  "United States": "🇺🇸",
  USA: "🇺🇸",
  "United States of America": "🇺🇸",
  Uruguay: "🇺🇾",
  Uzbekistan: "🇺🇿",
  Wales: "\u{1F3F4}\u{E0067}\u{E0062}\u{E0077}\u{E006C}\u{E0073}\u{E007F}",
}

const normalizedFlagByTeamName = Object.fromEntries(
  Object.entries(flagByTeamName).map(([team, flag]) => [normalizeTeamName(team), flag])
)

const spanishTeamNameByNormalizedName: Record<string, string> = {
  algeria: "Argelia",
  argentina: "Argentina",
  australia: "Australia",
  austria: "Austria",
  belgium: "Bélgica",
  "bosnia and herzegovina": "Bosnia y Herzegovina",
  "bosnia herzegovina": "Bosnia y Herzegovina",
  brazil: "Brasil",
  "cape verde": "Cabo Verde",
  "cape verde islands": "Cabo Verde",
  "cabo verde": "Cabo Verde",
  canada: "Canadá",
  chile: "Chile",
  colombia: "Colombia",
  "costa rica": "Costa Rica",
  "south korea": "Corea del Sur",
  "korea republic": "Corea del Sur",
  "republic of korea": "Corea del Sur",
  "ivory coast": "Costa de Marfil",
  "cote d ivoire": "Costa de Marfil",
  croatia: "Croacia",
  curacao: "Curazao",
  denmark: "Dinamarca",
  ecuador: "Ecuador",
  egypt: "Egipto",
  england: "Inglaterra",
  france: "Francia",
  germany: "Alemania",
  ghana: "Ghana",
  haiti: "Haití",
  iran: "Irán",
  iraq: "Irak",
  italy: "Italia",
  jamaica: "Jamaica",
  japan: "Japón",
  jordan: "Jordania",
  mexico: "México",
  morocco: "Marruecos",
  netherlands: "Países Bajos",
  holland: "Países Bajos",
  "new zealand": "Nueva Zelanda",
  norway: "Noruega",
  panama: "Panamá",
  paraguay: "Paraguay",
  peru: "Perú",
  poland: "Polonia",
  portugal: "Portugal",
  qatar: "Catar",
  czechia: "Chequia",
  "czech republic": "Chequia",
  "dr congo": "RD Congo",
  "congo dr": "RD Congo",
  "democratic republic of the congo": "República Democrática del Congo",
  "saudi arabia": "Arabia Saudí",
  scotland: "Escocia",
  senegal: "Senegal",
  serbia: "Serbia",
  "south africa": "Sudáfrica",
  spain: "España",
  sweden: "Suecia",
  switzerland: "Suiza",
  turkey: "Turquía",
  turkiye: "Turquía",
  tunisia: "Túnez",
  ukraine: "Ucrania",
  "united arab emirates": "Emiratos Árabes Unidos",
  uae: "Emiratos Árabes Unidos",
  "united states": "Estados Unidos",
  usa: "Estados Unidos",
  "united states of america": "Estados Unidos",
  uruguay: "Uruguay",
  uzbekistan: "Uzbekistán",
  wales: "Gales",
}

export function flagForTeam(teamName: string) {
  return normalizedFlagByTeamName[normalizeTeamName(teamName)] ?? "⚽"
}

export function displayTeamName(teamName: string, language: "en" | "es") {
  if (language !== "es") return teamName
  return spanishTeamNameByNormalizedName[normalizeTeamName(teamName)] ?? teamName
}

function normalizeTeamName(value: string) {
  return value
    .normalize("NFKD")
    .replace(/\p{Diacritic}/gu, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim()
}
